<?php
// login form for advisors
?>
<div class="row">
        <div class="col-md-6">
            <p>Advisors can log in here with the provided username and password.</p>

            <form id="login-form" role="form" action="<?php echo Mage::getUrl('*/*/loginPost'); ?>" method="post">
                <div class="form-group">
                    <label class="sr-only" for="username">Username:</label>
                    <input type="text" class="required-entry form-control" id="username" name="username" placeholder="Username"/>
                </div>
                <div class="form-group">
                    <label class="sr-only" for="password">Password:</label>
                    <input type="password" class="required-entry form-control" id="password" name="password" placeholder="Password" />
                </div>
                <div class="form-group">
                    <button class="btn-sm btn-info" type="submit">Log In</button>
                </div>
            </form>
        </div>
</div>