<?php
// delegation view
?>

<div class="col-lg-12">
    <div class="page-header">
        <h3 id="delegation"><?php echo $this->getDelegationName(); ?></h3>
    </div>
    <div class="bs-example table-responsive">
        <table class="table table-striped table-hover ">
            <thead>
            <tr>
                <th>Delegate Name</th>
                <th>Youth Summit?</th>
                <th>Legislative Weekend?</th>
                <th>Bill Submission Status</th>
            </tr>
            </thead>
            <?php foreach($this->_getStudents() as $student):
                $summit = $student->getData('youth_summit');
                $weekend = $student->getData('legislative_weekend');
                /* @var $student Ymca_Registration_Model_Student */?>
            <tbody>
            <tr>
                <td><a href="<?php echo Mage::getUrl('*/*/view', array('id'=>$student->getId())); ?>"><?php echo $student->getName(); ?><a></td>
                <td><span class="label label-<?php echo $this->getCssClasses($summit)?>"><?php echo $this->getValue($summit)?></span></td>
                <td><span class="label label-<?php echo $this->getCssClasses($weekend)?>"><?php echo $this->getValue($weekend)?></span> </td>
                <td><?php echo $this->getBillCell($student)?></td>
            </tr>
            </tbody>
            <?php endforeach; ?>
        </table>
    </div>
</div>