<?php
// template to edit a student (useredit.html)

// overview section ?>
<form id="editstudent" action="<?php echo Mage::getUrl('*/*/editPost'); ?>" method="POST">
<input name="id" type="hidden" value="<?php echo $this->getStudentId()?>" />
    <div class="col-lg-6">
        <div class="bs-example bs-example-type">
            <h1><input id="first_name" name="first_name" class="form-control inputDefault" type="text" value="<?php echo $this->getFirstName()?>" placeholder="First Name" required>
            <input id="last_name" name="last_name" class="form-control inputDefault" type="text" value="<?php echo $this->getLastName()?>" placeholder="Last Name" required></h1>
        </div>
    </div>
    <div class="col-lg-6">
    </div>
<div class="row">
    <div class="col-lg-8">
        <div class="bs-example table-responsive">
            <table class="table table-striped table-hover ">
                <tbody>
                <tr>
                    <td><label for="year">Year in Program</label></td>
                    <td>
                        <div class="form-group">
                            <div class="col-lg-10">
                                <select name="years" class="form-control-sm" id="year" value="<?php echo $this->getYears()?>">
                                    <option <?php echo $this->_selected('years', 1)?> value="1">1</option>
                                    <option <?php echo $this->_selected('years', 2)?> value="2">2</option>
                                    <option <?php echo $this->_selected('years', 3)?> value="3">3</option>
                                    <option <?php echo $this->_selected('years', 4)?> value="4">4</option>
                                </select>
                            </div>
                    </td>
                </tr>
                <tr>
                    <td><label for="grade">Grade</label></td>
                    <td>
                        <div class="form-group">
                            <div class="col-lg-10">
                                <select name="grade" class="form-control-sm" id="grade" value="<?php echo $this->getGrade()?>">
                                    <option <?php echo$this->_selected('grade', 9)?> value="9">9</option>
                                    <option <?php echo$this->_selected('grade', 10)?> value="10">10</option>
                                    <option <?php echo$this->_selected('grade', 11)?> value="11">11</option>
                                    <option <?php echo$this->_selected('grade', 12)?> value="12">12</option>
                            </div>
                    </td>
                </tr>
                <tr>
                    <td><label for="ethnicity">Ethnicity</label></td>
                    <td>
                        <div class="form-group">
                            <div class="col-lg-10">
                                <select name="ethnicity" class="form-control-sm" id="ethnicity" value="<?php echo$this->getEthnicity()?>">
                                    <option <?php echo $this->_selected('ethnicity', 'Unknown')?> >Unknown</option>
                                    <option <?php echo $this->_selected('ethnicity', 'White')?> >White</option>
                                    <option <?php echo $this->_selected('ethnicity', 'Hispanic or Latino')?> >Hispanic or Latino</option>
                                    <option <?php echo $this->_selected('ethnicity', 'Black or African American')?> >Black or African American</option>
                                    <option <?php echo $this->_selected('ethnicity', 'Native American or American Indian')?> >Native American or American Indian</option>
                                    <option <?php echo $this->_selected('ethnicity', 'Asian / Pacific Islander')?> >Asian / Pacific Islander</option>
                                    <option <?php echo $this->_selected('ethnicity', 'Other')?> >Other</option>
                                 </select>
                            </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="bs-example">
            <div class="list-group">
                <a onclick="document.forms['editstudent'].submit();return false;" class="list-group-item list-group-item-success">Save Delegate</a>
                <a onclick="location.href='<?php echo Mage::getUrl('*/*/view', array('id'=>$this->getStudentId()));?>';" class="list-group-item">Cancel</a>
                <a href="<?php echo Mage::getUrl('*/*/delete', array('student_id'=>$this->getStudentId())); ?>" class="list-group-item list-group-item-danger">Delete Delegate</a>
            </div>
        </div>
    </div>
</div>

<div class="col-lg-12">
    <div class="page-header">
        <h3 id="events">Events Registered</h3>
    </div>
    <div class="bs-example table-responsive">
        <table class="table table-striped table-hover ">
            <thead>
            <tr>
                <th>Event Name</th>
                <th>Attended/Planning to Attend?</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td><label for="youth_summit_select">Youth Summit 2013-2014</label></td>
                <td>
                    <div class="form-group">
                        <div class="col-lg-10">
                            <select name="youth_summit" class="form-control-sm" id="youth_summit_select">
                                <option value="0" <?php echo$this->_selected('youth_summit', 0)?>>Unknown</option>
                                <option value="1" <?php echo$this->_selected('youth_summit', 1)?>>Yes</option>
                                <option value="-1" <?php echo$this->_selected('youth_summit', -1)?>>No</option>
                            </select>
                        </div>
                </td>
            </tr>
            <tr>
                <td>Legislative Weekend 2013-2014</td>
                <td>
                    <div class="form-group">
                        <div class="col-lg-10">
                            <select name="legislative_weekend" class="form-control-sm" id="select">
                                <option value="0" <?php echo$this->_selected('legislative_weekend', 0)?>>Unknown</option>
                                <option value="1" <?php echo$this->_selected('legislative_weekend', 1)?>>Yes</option>
                                <option value="-1" <?php echo$this->_selected('legislative_weekend', -1)?>>No</option>
                            </select>
                        </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
<div class="col-lg-12">
    <div class="page-header">
        <h3 id="emergency">Emergency Contact</h3>
    </div>
    <div class="row">
        <div class="col-xs-4">
            <label for="emergency_name" class="sr-only">Emergency Contact's Name</label>
            <input id="emergency_name" name="emergency_name" class="form-control input-sm" type="text" value="<?php echo$this->getEmergencyName()?>" placeholder="Emergency Contact Name" />
        </div>
        <div class="col-xs-4">
            <label for="emergency_relation" class="sr-only">Emergency Contact's Relationship to Student</label>
            <input id="emergency_relation" name="emergency_relation" class="form-control input-sm" type="text" value="<?php echo$this->getEmergencyRelation()?>" placeholder="Relationship to Student" />
        </div>
        <div class="col-xs-4">
            <label for="emergency_number" class="sr-only">Emergency Contact's Phone Number</label>
            <input id="emergency_number" name="emergency_number" class="form-control input-sm" type="text" value="<?php echo$this->getEmergencyNumber()?>" placeholder="Phone Number" />
        </div>
    </div>
</div>
<?php
 // transportation
 /*
<div class="col-lg-12">
    <div class="page-header">
        <h3 id="transporation">Transportation</h3>
    </div>
    <div class="bs-example table-responsive">
        <table class="table table-striped table-hover ">
            <thead>
            <tr>
                <th>Year</th>
                <th>Event Name</th>
                <th>Transporation Status</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>2013-2014</td>
                <td>To Youth Summit: </td>
                <td>
                    <div class="form-group">
                        <div class="col-lg-10">
                            <select name="to_youth_summit" class="form-control-sm" id="select">
                                <option value=0>Unknown</option>
                                <option value=1>Yes</option>
                                <option value=-1>No</option>
                            </select>
                        </div>
                </td>
            </tr>
            <tr>
                <td>2013-2014</td>
                <td>From Youth Summit: </td>
                <td>
                    <div class="form-group">
                        <div class="col-lg-10">
                            <select name="from_youth_summit" class="form-control-sm" id="select">
                                <option value=0>Unknown</option>
                                <option value=1>Yes</option>
                                <option value=-1>No</option>
                            </select>
                        </div>
                </td>
            </tr>
            <tr>
                <td>2013-2014</td>
                <td>To Legislative Weekend: </td>
                <td>
                    <div class="form-group">
                        <div class="col-lg-10">
                            <select name="to_legislative_weekend" class="form-control-sm" id="select">
                                <option value=0>Unknown</option>
                                <option value=1>Yes</option>
                                <option value=-1>No</option>
                            </select>
                        </div>
                </td>
            </tr>
            <tr>
                <td>2013-2014</td>
                <td>From Legislative Weekend: </td>
                <td>
                    <div class="form-group">
                        <div class="col-lg-10">
                            <select name="from_legislative_weekend" class="form-control-sm" id="select">
                                <option value=0>Unknown</option>
                                <option value=1>Yes</option>
                                <option value=-1>No</option>
                            </select>
                        </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
*/?>
</form>

